# Generated by Django 5.2.11 on 2026-02-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("author_name", models.CharField(max_length=200)),
                ("author_email", models.EmailField(max_length=254)),
                ("cover_image_url", models.URLField(blank=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("is_public", models.BooleanField(default=False)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("website_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["slug"], name="podcast_pod_slug_c90982_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("unpublished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("episode_number", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                ("show_notes", models.TextField(blank=True)),
                ("audio_url", models.URLField()),
                (
                    "audio_duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "audio_file_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("cover_image_url", models.URLField(blank=True)),
                ("is_explicit", models.BooleanField(default=False)),
                ("transcript", models.TextField(blank=True)),
                ("chapters", models.TextField(blank=True)),
                ("companion_resources", models.JSONField(blank=True, default=dict)),
                ("report_text", models.TextField(blank=True)),
                ("sources_text", models.TextField(blank=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcast.podcast",
                    ),
                ),
            ],
            options={
                "ordering": ["episode_number"],
                "indexes": [
                    models.Index(fields=["slug"], name="podcast_epi_slug_f3152a_idx")
                ],
                "unique_together": {("podcast", "episode_number"), ("podcast", "slug")},
            },
        ),
    ]
