# Generated by Django 5.2.11 on 2026-02-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="audio_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="episode_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EpisodeArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="podcast.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("episode", "title")},
            },
        ),
    ]
