# Generated by Django 5.2.11 on 2026-02-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_episode_status_alter_episode_audio_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "opening_script",
                    models.TextField(
                        blank=True,
                        help_text="Custom opening script for NotebookLM audio generation",
                    ),
                ),
                (
                    "closing_script",
                    models.TextField(
                        blank=True,
                        help_text="Custom closing script for NotebookLM audio generation",
                    ),
                ),
                (
                    "depth_level",
                    models.CharField(
                        choices=[
                            ("accessible", "Accessible"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="accessible",
                        help_text="How much baseline knowledge to assume",
                        max_length=20,
                    ),
                ),
                (
                    "sponsor_break",
                    models.BooleanField(
                        default=True,
                        help_text="Include sponsor splice point in episodes",
                    ),
                ),
                (
                    "companion_access",
                    models.CharField(
                        choices=[("public", "Public"), ("gated", "Gated")],
                        default="public",
                        help_text="Access level for companion resources",
                        max_length=20,
                    ),
                ),
                (
                    "podcast",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="podcast.podcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast Config",
                "verbose_name_plural": "Podcast Configs",
            },
        ),
    ]
