# Generated by Django 5.2.11 on 2026-02-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0003_add_podcast_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodeartifact",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="episodeartifact",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
