# Generated by Django 5.2.11 on 2026-02-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0004_add_url_to_episode_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodeartifact",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="episodeartifact",
            name="workflow_context",
            field=models.CharField(
                blank=True,
                help_text="Workflow step(s) that produced and/or consume this artifact, by name (not number).",
                max_length=200,
            ),
        ),
    ]
