# Generated by Django 6.0.2 on 2026-02-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0005_add_description_and_workflow_context_to_artifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "current_step",
                    models.CharField(
                        help_text='Current workflow step name, e.g. "Research Gathering", "Synthesis".',
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused_for_human", "Paused for Human"),
                            ("paused_at_gate", "Paused at Gate"),
                            ("failed", "Failed"),
                            ("complete", "Complete"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "blocked_on",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of the input or action needed to unblock the workflow.",
                        max_length=200,
                    ),
                ),
                (
                    "history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of dicts: [{step, status, started_at, completed_at, error}].",
                    ),
                ),
                (
                    "agent_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Anthropic agent session ID for resumable workflows.",
                        max_length=100,
                    ),
                ),
                (
                    "episode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="podcast.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
