# Generated by Django 6.0.2 on 2026-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0006_episodeworkflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodeworkflow",
            name="current_step",
            field=models.CharField(
                default="Setup",
                help_text='Current workflow step name, e.g. "Research Gathering", "Synthesis".',
                max_length=100,
            ),
        ),
    ]
