# Generated by Django 6.0.2 on 2026-02-20 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0007_add_default_to_current_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="apple_podcasts_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcasts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="spotify_url",
            field=models.URLField(blank=True),
        ),
    ]
