# Generated by Django 6.0.2 on 2026-02-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast", "0008_podcast_apple_podcasts_url_podcast_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"ordering": ["topic_series", "episode_number"]},
        ),
        migrations.AddField(
            model_name="episode",
            name="topic_series",
            field=models.CharField(
                blank=True,
                help_text="Topic series name for grouping episodes (e.g. 'Cardiovascular Health')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="unpublished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
