# Generated by Django 6.0.2 on 2026-02-23 16:43

from django.db import migrations
from django.utils import timezone


def populate_yudame_research_metadata(apps, schema_editor):
    Podcast = apps.get_model("podcast", "Podcast")
    try:
        p = Podcast.objects.get(slug="yudame-research")
    except Podcast.DoesNotExist:
        return
    p.published_at = p.published_at or timezone.now()
    p.cover_image_url = "https://research.yuda.me/podcast/cover.png"
    p.apple_podcasts_url = (
        "https://podcasts.apple.com/us/podcast/yudame-research-podcast/id1862329179"
    )
    p.spotify_url = "https://open.spotify.com/show/32xUME8x4FN1DcNwBOrYfc"
    p.website_url = "https://research.yuda.me"
    p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0010_rename_topic_series_to_tags"),
    ]

    operations = [
        migrations.RunPython(
            populate_yudame_research_metadata,
            migrations.RunPython.noop,
        ),
    ]
