# Generated by Django 6.0.3 on 2026-04-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_convert_image_document_to_inherit_upload"),
        ("podcast", "0012_remove_podcast_is_public_podcast_privacy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "subscriber_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Subscriber's email address (denormalized from Stripe)",
                        max_length=254,
                    ),
                ),
                (
                    "subscriber_name",
                    models.CharField(
                        blank=True,
                        help_text="Subscriber's full name (denormalized from Stripe)",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("churned", "Churned")],
                        default="active",
                        help_text="Subscription lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("biweekly", "Biweekly")],
                        default="weekly",
                        help_text="How often the subscriber receives new episodes",
                        max_length=20,
                    ),
                ),
                (
                    "length_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Target episode length in minutes"
                    ),
                ),
                (
                    "topic_focus",
                    models.TextField(
                        blank=True,
                        help_text="Subscriber-specified topic focus for episode curation",
                    ),
                ),
                (
                    "next_drop_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled datetime for the next episode delivery",
                        null=True,
                    ),
                ),
                (
                    "do_not_email",
                    models.BooleanField(
                        default=False,
                        help_text="Suppress all outbound emails for this subscriber",
                    ),
                ),
                (
                    "podcast",
                    models.OneToOneField(
                        help_text="The podcast this subscriber receives",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_subscription",
                        to="podcast.podcast",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        help_text="Billing subscription record from Stripe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_subscription",
                        to="common.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast Subscription",
                "verbose_name_plural": "Podcast Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
