"""The SSE parser, lifted from spike 03 and made pure. Plan 04, Modules.

Every model call is forced to stream upstream, so this module is the one
place that turns provider bytes into what the log and a non-streaming
client need: the usage the provider billed, the content blocks, and the
stop reason. Nothing here touches a connection, a clock, or the gateway's
state, so the properties can drive it with generated bytes (Properties P3).

A stream that never reached `message_delta` is truncated: a cut, a client
drop, an upstream timeout, or a process that died mid-call. Its usage is
charged at the reserve rather than at what arrived, which is the
fail-closed direction and what `charged_reserved` marks (plan 04, step 7).
"""

import json
from dataclasses import dataclass, field

from schemas.gateway import Usage

USAGE_FIELDS = (
    "input_tokens",
    "output_tokens",
    "cache_creation_input_tokens",
    "cache_read_input_tokens",
)


@dataclass(frozen=True)
class Parsed:
    """What one upstream stream said. `complete` is the whole truth about
    whether the provider finished: only `message_delta` carries the final
    output count and the stop reason."""

    usage: dict[str, int] = field(default_factory=dict)
    blocks: list[dict] = field(default_factory=list)
    stop_reason: str | None = None
    stop_sequence: str | None = None
    message: dict = field(default_factory=dict)
    started: bool = False
    complete: bool = False

    def __iter__(self):
        """`usage, blocks, stop_reason = parse(events)`, the triple plan 04's
        module table names."""
        return iter((self.usage, self.blocks, self.stop_reason))


# ---------------------------------------------------------------------------
# Framing


def split_events(buffer: str) -> tuple[list[dict], str]:
    """Every complete event in the buffer, and what is left over. The
    streaming path feeds chunks in and keeps the remainder; `iter_events`
    drops it."""
    events: list[dict] = []
    while "\n\n" in buffer:
        block, buffer = buffer.split("\n\n", 1)
        data = []
        for line in block.splitlines():
            if line.startswith("data:"):
                data.append(line[5:].removeprefix(" "))
        if not data:
            continue
        try:
            parsed = json.loads("\n".join(data))
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            events.append(parsed)
    return events, buffer


def iter_events(data: bytes | str) -> list[dict]:
    """Every event in a complete stream. A trailing partial event is not an
    event, so it is dropped."""
    text = data.decode() if isinstance(data, bytes) else data
    events, _ = split_events(text)
    return events


# ---------------------------------------------------------------------------
# Folding


def parse(events) -> Parsed:
    """Fold the provider's events into usage, blocks, and a stop reason.

    An event type this does not know is ignored, including the error event
    the gateway itself appends on a cut: the log records the cut, and a
    parser that raised on an unexpected type would lose the usage that
    arrived before it.
    """
    usage: dict[str, int] = {}
    blocks: list[dict] = []
    message: dict = {}
    stop_reason = None
    stop_sequence = None
    started = False
    complete = False

    for event in events:
        kind = event.get("type")
        if kind == "message_start":
            started = True
            body = dict(event.get("message") or {})
            usage.update(_usage(body.pop("usage", None)))
            body.pop("content", None)
            message = body
        elif kind == "content_block_start":
            block = dict(event.get("content_block") or {})
            if block.get("type") == "tool_use":
                block["_json"] = ""
                block.setdefault("input", {})
            elif block.get("type") == "text":
                block.setdefault("text", "")
            blocks.append(block)
        elif kind == "content_block_delta":
            index = event.get("index")
            if not isinstance(index, int) or not 0 <= index < len(blocks):
                continue
            delta = event.get("delta") or {}
            if delta.get("type") == "text_delta":
                blocks[index]["text"] = blocks[index].get("text", "") + delta.get(
                    "text", ""
                )
            elif delta.get("type") == "input_json_delta":
                blocks[index]["_json"] = blocks[index].get("_json", "") + delta.get(
                    "partial_json", ""
                )
        elif kind == "message_delta":
            complete = True
            usage.update(_usage(event.get("usage")))
            delta = event.get("delta") or {}
            stop_reason = delta.get("stop_reason", stop_reason)
            stop_sequence = delta.get("stop_sequence", stop_sequence)

    return Parsed(
        usage=usage,
        blocks=[_finish(b) for b in blocks],
        stop_reason=stop_reason,
        stop_sequence=stop_sequence,
        message=message,
        started=started,
        complete=complete,
    )


def _usage(reported) -> dict[str, int]:
    """The four token fields the provider bills on, and only those. A field
    reported as null is a field the provider did not report, not a zero."""
    if not isinstance(reported, dict):
        return {}
    return {
        k: int(reported[k])
        for k in USAGE_FIELDS
        if isinstance(reported.get(k), (int, float))
        and not isinstance(reported[k], bool)
    }


def _finish(block: dict) -> dict:
    """A `tool_use` block's arguments arrive as partial JSON. Truncated JSON
    parses as nothing, which is what the SDK's own accumulator leaves when a
    block never closed."""
    block = dict(block)
    if "_json" not in block:
        return block
    raw = block.pop("_json")
    try:
        block["input"] = json.loads(raw) if raw else {}
    except json.JSONDecodeError:
        block["input"] = {}
    return block


# ---------------------------------------------------------------------------
# Assembling


def assemble(parsed: Parsed) -> dict:
    """The Message a non-streaming client gets: what the provider would have
    returned had the gateway not forced the stream (plan 04, step 6)."""
    message = dict(parsed.message)
    message.setdefault("type", "message")
    message.setdefault("role", "assistant")
    message["content"] = [dict(b) for b in parsed.blocks]
    message["stop_reason"] = parsed.stop_reason
    message["stop_sequence"] = parsed.stop_sequence
    message["usage"] = {k: parsed.usage.get(k, 0) for k in USAGE_FIELDS}
    return message


def usage_of(
    parsed: Parsed, *, max_tokens: int, estimated_input: int, usd_micros: int = 0
) -> Usage:
    """The `Usage` the closing row carries.

    A complete stream is billed at what the provider reported. A truncated
    one is billed at the reserve: `max_tokens` of output, and the input
    `message_start` reported or the pre-check's estimate if it never
    arrived. `usd_micros` is priced by the caller, since prices are the
    seat file's (plan 04, step 7).
    """
    reserved = not parsed.complete
    reported = {k: parsed.usage.get(k, 0) for k in USAGE_FIELDS}
    if reserved:
        reported["output_tokens"] = max_tokens
        if not parsed.started:
            reported["input_tokens"] = estimated_input
    return Usage(**reported, usd_micros=usd_micros, charged_reserved=reserved)
