# Generated by Django 3.1 on 2020-10-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_telegrambotmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotmembership',
            name='telegram_user_dict',
            field=models.JSONField(default=dict),
        ),
    ]
