# Schema documented at https://render.com/docs/yaml-spec
previews:
  generation: manual

services:
  # Production web service
  - type: web
    name: cuttlefish-production
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn settings.wsgi:application --bind 0.0.0.0:$PORT --timeout 180 --keep-alive 5 --worker-connections 1000 --preload
    repo: https://github.com/tomcounsell/cuttlefish.git
    branch: main
    region: virginia
    plan: starter
    healthCheckPath: /health/
    envVars:
      - key: PORT
        value: 8000
      - key: DEPLOYMENT_TYPE
        value: PRODUCTION
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: redis-production
          property: connectionString
      - fromGroup: cuttlefish

  - type: keyvalue
    name: redis-production
    region: virginia
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow-all
    plan: starter
    maxmemoryPolicy: allkeys-lru
