"""reflections/audits/hooks_audit.py — Per-project Claude Code hooks audit.

What it does: Scans each project's `logs/hooks.log` for recent (last 24h)
    errors and validates hook configuration in BOTH the project-scope
    `.claude/settings.json` AND the user-scope `~/.claude/settings.json`
    (Stop/SubagentStop must carry a crash guard; hook script paths must exist,
    in either scope). Also scans `.claude/agents/*.md` for agent-level
    `hooks:` frontmatter blocks and reports them informationally as an
    additional declared hooks surface (not owned/generated by any manifest,
    but must not be silently omitted).
Cadence: 86400s (hook config and log volume change slowly; daily catches drift)
Failure modes:
    - neither hooks.log nor settings.json (project or user) present -> project
      skipped via skip_if
    - hooks.log scan exception -> logged, error_count left at last value
    - settings.json parse error (either scope) -> logged, counted as one
      settings issue for that scope
    - agent-hooks frontmatter parse error -> logged, skipped (informational
      surface only, never fails the audit)
Related reflections:
    - skills-audit: sibling per-project audit over the same project list
See also: config/reflections.yaml (declaration), docs/features/reflections.md
"""

from __future__ import annotations

import json
import logging
import re
from datetime import timedelta
from pathlib import Path
from typing import Any

import yaml

from reflections.utilities import (
    PROJECT_ROOT,
    extract_structured_errors,
    run_per_project_audit,
)

logger = logging.getLogger("reflections.auditing")

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)


def _validate_hook_settings(
    settings_path: Path, repo_root: Path, scope_label: str
) -> tuple[list[str], int]:
    """Validate one scope's ``settings.json`` hooks block.

    Applies the same two checks to whichever scope is passed in:
    Stop/SubagentStop hooks must carry a crash guard, and every registered
    command's script path must exist on disk. Findings are prefixed with
    ``[<scope_label>]`` so a reader can tell which scope a FAIL/WARN
    belongs to.

    The crash guard is satisfied by either exit_policy the manifest can
    generate for a Stop hook (#2527): ``suppress``'s ``|| true``, or
    ``deny-only``'s ``__hook_rc`` capture. Both map a crashing hook to exit 0,
    which is what this check is for — a bare command lets a traceback wedge
    turn-end fleet-wide.

    ``repo_root`` is only used to resolve project-relative
    ``$CLAUDE_PROJECT_DIR``-style paths; absolute paths (as used by the
    user scope) resolve directly regardless of ``repo_root`` because
    ``Path.__truediv__`` returns the right operand unchanged when it is
    already absolute.
    """
    findings: list[str] = []
    issues = 0

    if not settings_path.exists():
        return findings, issues

    try:
        settings = json.loads(settings_path.read_text())
    except (json.JSONDecodeError, OSError) as e:
        logger.warning(f"Failed to parse {scope_label} settings.json: {e}")
        findings.append(f"[{scope_label}] FAIL: could not parse settings.json: {e}")
        return findings, 1

    hooks = settings.get("hooks", {})

    for event_type, matchers in hooks.items():
        for matcher_block in matchers:
            for hook in matcher_block.get("hooks", []):
                cmd = hook.get("command", "")
                has_crash_guard = "|| true" in cmd or "__hook_rc" in cmd

                if event_type in ("Stop", "SubagentStop") and not has_crash_guard:
                    findings.append(
                        f"[{scope_label}] FAIL: {event_type} hook missing crash guard "
                        f"(|| true or __hook_rc): {cmd[:60]}"
                    )
                    issues += 1

                for part in cmd.replace("|| true", "").split():
                    if part.endswith(".py") or part.endswith(".sh"):
                        script_path = part.replace('"$CLAUDE_PROJECT_DIR"/', "").replace(
                            "$CLAUDE_PROJECT_DIR/", ""
                        )
                        full_path = repo_root / script_path
                        if not full_path.exists():
                            findings.append(
                                f"[{scope_label}] WARN: Hook script not found: {script_path}"
                            )
                            issues += 1
                        break

    return findings, issues


def _scan_agent_hooks(repo_root: Path) -> list[str]:
    """Scan `.claude/agents/*.md` for agent-level `hooks:` frontmatter blocks.

    This surface is declared per-agent-file, not owned or generated by any
    manifest/generator. It is reported informationally (never FAIL-gated)
    so it is visible in the audit report rather than silently omitted -- per
    the "Data ownership" note in docs/plans/hook-registration-manifest-dispatcher.md.
    """
    findings: list[str] = []
    agents_dir = repo_root / ".claude" / "agents"
    if not agents_dir.is_dir():
        return findings

    for agent_file in sorted(agents_dir.glob("*.md")):
        try:
            text = agent_file.read_text()
        except OSError as e:
            logger.warning(f"Failed to read {agent_file}: {e}")
            continue

        match = _FRONTMATTER_RE.match(text)
        if not match:
            continue

        try:
            frontmatter: Any = yaml.safe_load(match.group(1))
        except yaml.YAMLError as e:
            logger.warning(f"Failed to parse frontmatter in {agent_file}: {e}")
            continue

        if not isinstance(frontmatter, dict):
            continue

        agent_hooks = frontmatter.get("hooks")
        if not agent_hooks or not isinstance(agent_hooks, dict):
            continue

        events = ", ".join(sorted(agent_hooks.keys()))
        findings.append(
            f"[agent-hooks] INFO: {agent_file.name} declares agent-level hooks for: {events}"
        )

    return findings


def _hooks_audit_for_project(project: dict) -> dict:
    """Per-project body for hooks-audit.

    Scans the project's ``logs/hooks.log`` for recent errors, validates
    hook configuration in BOTH ``.claude/settings.json`` (project scope)
    and ``~/.claude/settings.json`` (user scope), and scans
    ``.claude/agents/*.md`` for agent-level hooks blocks (informational).
    """
    import time as _time

    from bridge.utc import utc_now

    wd = project.get("working_directory", "")
    repo_root = Path(wd) if wd else PROJECT_ROOT

    findings: list[str] = []
    error_count = 0
    settings_issues = 0
    t0 = _time.time()

    hooks_log = repo_root / "logs" / "hooks.log"
    if hooks_log.exists():
        try:
            errors = extract_structured_errors(hooks_log)
            cutoff = (utc_now() - timedelta(days=1)).strftime("%Y-%m-%d")
            recent = [e for e in errors if e.get("timestamp", "") >= cutoff]
            error_count = len(recent)
            if recent:
                hook_names = set()
                for e in recent:
                    msg = e.get("message", "")
                    parts = msg.split(" - ")
                    if parts:
                        hook_names.add(parts[0].strip())
                names = ", ".join(sorted(hook_names)) or "unknown"
                findings.append(f"{error_count} hook error(s) in last 24h from: {names}")

            # Dedicated signal for the hook_python shim's fail-open branch
            # (issue #2503, Risk 5). When the main checkout is relocated,
            # renamed, or its .venv removed, the shim exits 0 without running
            # any Python, silently disabling every project hook. That is the
            # same silent-disablement class this issue fixes, merely relocated,
            # so it gets its OWN finding rather than folding into the aggregate
            # count above.
            #
            # This detector is reachable because the shim itself appends the
            # record: on its fail-open branch it writes one line to
            # logs/hooks.log in log_hook_error's exact format, carrying the same
            # message string it sends to stderr. No hook Python runs on that
            # branch, so nothing else could write it. The marker below is that
            # message's stable prefix, and the shim's own regression test
            # (tests/unit/test_hook_interpreter.py) plus the audit test both
            # assert against the shim's REAL execution output, not a fixture --
            # so the audit and the shim cannot drift apart silently.
            shim_marker = "hook_python: no repo venv interpreter found"
            shim_hits = sum(1 for e in recent if shim_marker in e.get("message", ""))
            if shim_hits:
                findings.append(
                    f"hook_python shim failing open ({shim_hits} in last 24h): "
                    "no repo venv interpreter found — project hooks are silently disabled"
                )
        except Exception as e:
            logger.warning(f"Failed to scan hooks.log: {e}")

    project_settings_path = repo_root / ".claude" / "settings.json"
    project_findings, project_issues = _validate_hook_settings(
        project_settings_path, repo_root, "project"
    )
    findings.extend(project_findings)
    settings_issues += project_issues

    user_settings_path = Path.home() / ".claude" / "settings.json"
    user_findings, user_issues = _validate_hook_settings(user_settings_path, Path.home(), "user")
    findings.extend(user_findings)
    settings_issues += user_issues

    findings.extend(_scan_agent_hooks(repo_root))

    return {
        "status": "ok",
        "findings": findings,
        "summary": f"Hooks audit: {error_count} log errors, {settings_issues} settings issues",
        "duration": _time.time() - t0,
    }


def run() -> dict:
    """Audit Claude Code hooks per project.

    Iterates every local project with EITHER ``logs/hooks.log`` OR
    ``.claude/settings.json`` present (skips projects with neither). The
    user-scope ``~/.claude/settings.json`` and any ``.claude/agents/*.md``
    hooks blocks are always additionally inspected when present, regardless
    of the project's own skip decision inputs.

    Hotfix (sibling of PR #1056): the per-project body does only sync I/O
    (``extract_structured_errors``, ``json.loads``, ``Path.read_text``,
    ``Path.exists``) with no awaits — see ``test_event_loop_safe_callables_are_sync``.
    """

    def skip_if(repo_root: Path) -> bool:
        return not (
            (repo_root / "logs" / "hooks.log").exists()
            or (repo_root / ".claude" / "settings.json").exists()
        )

    return run_per_project_audit(_hooks_audit_for_project, skip_if=skip_if, name="hooks-audit")
