# Generated by Django 6.0.2 on 2026-02-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quickbooksconnection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="quickbooksconnection",
            name="organization",
        ),
        migrations.DeleteModel(
            name="MCPSession",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="QuickBooksConnection",
        ),
    ]
