# Generated by Django 5.2.5 on 2026-01-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Brand or common name of the medication",
                        max_length=200,
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True,
                        help_text="Generic/scientific name if different from brand name",
                        max_length=200,
                    ),
                ),
                (
                    "medication_type",
                    models.CharField(
                        choices=[
                            ("drug", "Prescription Drug"),
                            ("otc", "OTC Medicine"),
                            ("supplement", "Supplement/Vitamin"),
                        ],
                        default="drug",
                        max_length=20,
                    ),
                ),
                (
                    "known_interactions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Known drug-drug interactions (medication IDs and warnings)",
                    ),
                ),
                (
                    "food_timing",
                    models.CharField(
                        choices=[
                            ("with_food", "Take with food"),
                            ("empty_stomach", "Take on empty stomach"),
                            ("anytime", "Any time"),
                        ],
                        default="anytime",
                        help_text="When this medication should be taken relative to meals",
                        max_length=20,
                    ),
                ),
                (
                    "common_dosages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Common dosage forms and strengths (e.g., ['10mg tablet', '20mg tablet'])",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="drugs_medic_name_a22997_idx"),
                    models.Index(
                        fields=["medication_type"],
                        name="drugs_medic_medicat_f6f4ac_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMealSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_author_anonymous", models.BooleanField(default=False)),
                ("authored_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "breakfast_time",
                    models.TimeField(
                        blank=True, help_text="Typical breakfast time", null=True
                    ),
                ),
                (
                    "lunch_time",
                    models.TimeField(
                        blank=True, help_text="Typical lunch time", null=True
                    ),
                ),
                (
                    "dinner_time",
                    models.TimeField(
                        blank=True, help_text="Typical dinner time", null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Meal Schedule",
                "verbose_name_plural": "User Meal Schedules",
            },
        ),
        migrations.CreateModel(
            name="UserMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_author_anonymous", models.BooleanField(default=False)),
                ("authored_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "dosage",
                    models.CharField(
                        help_text="e.g., '10mg', '2 tablets', '1 capsule'",
                        max_length=100,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., 'once daily', 'twice daily', 'as needed'",
                        max_length=100,
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("anytime", "Any time"),
                        ],
                        default="anytime",
                        help_text="Preferred time of day to take this medication",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user is currently taking this medication",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this medication (why taking it, prescribing doctor, etc.)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_medications",
                        to="drugs.medication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "medication__name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="drugs_userm_user_id_603bd2_idx",
                    )
                ],
            },
        ),
    ]
