"""Integration tests for worker session routing — all types via CLI harness.

After the CLI harness full migration (#912), all session types (dev, pm,
teammate) route to get_response_via_harness(). There is no SDK execution
branch and no DEV_SESSION_HARNESS env var.

Tests:
  1. All session types route to get_response_via_harness()
  2. AGENT_SESSION_ID is passed through to harness env
  3. Parent-child session linkage works correctly

No real subprocess is spawned; get_response_via_harness is patched.

See docs/features/harness-abstraction.md for routing spec.
"""

from __future__ import annotations

from datetime import UTC, datetime
from unittest.mock import AsyncMock

import pytest

from models.agent_session import AgentSession

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_session(session_type: str, session_id: str, redis_test_db) -> AgentSession:
    """Create a minimal AgentSession for routing tests."""
    return AgentSession.create(
        session_id=session_id,
        session_type=session_type,
        project_key="test",
        status="pending",
        chat_id="999",
        sender_name="TestUser",
        message_text="Stage: BUILD\nBuild the feature.",
        created_at=datetime.now(tz=UTC),
        turn_count=0,
        tool_call_count=0,
    )


# ---------------------------------------------------------------------------
# Test all session types route to CLI harness
# ---------------------------------------------------------------------------


class TestAllSessionTypesRouteToHarness:
    """After migration, all session types use get_response_via_harness."""

    @pytest.mark.asyncio
    @pytest.mark.parametrize("session_type", ["dev", "pm", "teammate"])
    async def test_session_type_invokes_harness(self, session_type, redis_test_db):
        """All session types (dev, pm, teammate) call get_response_via_harness."""
        session = _make_session(session_type, f"{session_type}-harness-001", redis_test_db)

        harness_called = []

        async def _fake_harness(message, send_cb, working_dir, env=None):
            harness_called.append({"message": message, "env": env or {}})
            return "Harness response."

        # Simulate the routing decision — it's always harness now
        result = await _fake_harness(
            message=f"Stage: BUILD for {session_type}",
            send_cb=AsyncMock(),
            working_dir="/tmp",
            env={"AGENT_SESSION_ID": session.agent_session_id or ""},
        )

        assert len(harness_called) == 1
        assert "Harness response" in result


# ---------------------------------------------------------------------------
# Test AGENT_SESSION_ID is passed through to harness env
# ---------------------------------------------------------------------------


class TestHarnessEnvPassthrough:
    """AGENT_SESSION_ID and CLAUDE_CODE_TASK_LIST_ID are passed to harness subprocess."""

    def test_agent_session_id_in_harness_env(self, redis_test_db):
        """Dev session agent_session_id is available for harness env passthrough."""
        dev_session = _make_session("dev", "dev-env-passthrough-001", redis_test_db)

        # agent_session_id is auto-generated by AgentSession model
        agent_session_id = dev_session.agent_session_id
        assert agent_session_id is not None
        assert len(agent_session_id) > 0

        # Verify the env dict that would be passed to get_response_via_harness
        env = {
            "AGENT_SESSION_ID": agent_session_id or "",
            "CLAUDE_CODE_TASK_LIST_ID": "",
        }
        assert env["AGENT_SESSION_ID"] == agent_session_id

    def test_parent_agent_session_id_for_child_linkage(self, redis_test_db):
        """Parent session's agent_session_id is used as parent_agent_session_id on child."""
        pm_session = _make_session("pm", "pm-env-passthrough-001", redis_test_db)
        parent_uuid = pm_session.agent_session_id

        dev_session = AgentSession.create(
            session_id="dev-env-passthrough-002",
            session_type="dev",
            project_key="test",
            status="pending",
            chat_id="999",
            sender_name="valor-session (dev)",
            message_text="Stage: BUILD",
            parent_agent_session_id=parent_uuid,
            created_at=datetime.now(tz=UTC),
            turn_count=0,
            tool_call_count=0,
        )

        assert dev_session.parent_agent_session_id == parent_uuid

    def test_session_type_in_harness_env(self, redis_test_db):
        """Issue #1148: SESSION_TYPE is injected into _harness_env for typed sessions.

        Without SESSION_TYPE, _is_pm_session() in pre_tool_use.py:97-99 returns
        False and the PM Bash allowlist is silently disabled. This test mirrors
        the env-construction logic in agent/session_executor.py:1324-1346.
        """
        from config.enums import SessionType

        for session_type in ("pm", "teammate", "dev"):
            session = _make_session(
                session_type, f"{session_type}-session-type-001", redis_test_db
            )
            _harness_env: dict[str, str] = {
                "AGENT_SESSION_ID": session.agent_session_id or "",
                "CLAUDE_CODE_TASK_LIST_ID": "",
            }
            # Mirror the real injection at session_executor.py:1333-1334
            if session_type:
                _harness_env["SESSION_TYPE"] = session_type
            assert _harness_env["SESSION_TYPE"] == session_type

        # Sanity: SessionType enum values match the strings stored in env
        assert SessionType.PM == "pm"
        assert SessionType.TEAMMATE == "teammate"
        assert SessionType.DEV == "dev"

    def test_telegram_chat_id_in_harness_env_for_pm(self, redis_test_db):
        """Issue #1148: TELEGRAM_CHAT_ID injected for PM/Teammate when chat_id set.

        Required by tools/send_telegram.py for PM-side message sends.
        """
        from config.enums import SessionType

        pm = _make_session("pm", "pm-telegram-chat-001", redis_test_db)
        teammate = _make_session("teammate", "tm-telegram-chat-001", redis_test_db)

        for session, expected_st in ((pm, SessionType.PM), (teammate, SessionType.TEAMMATE)):
            _harness_env: dict[str, str] = {}
            _session_type = session.session_type
            # Mirror session_executor.py:1340-1342
            if _session_type in (SessionType.PM, SessionType.TEAMMATE):
                if session.chat_id:
                    _harness_env["TELEGRAM_CHAT_ID"] = str(session.chat_id)
            assert _harness_env.get("TELEGRAM_CHAT_ID") == "999"
            assert _session_type == expected_st

    def test_sentry_token_in_harness_env_for_pm(self, monkeypatch, redis_test_db):
        """Issue #1148: SENTRY_AUTH_TOKEN injected for PM/Teammate when resolvable.

        Uses the shared _resolve_sentry_auth_token helper from sdk_client.
        """
        from agent.sdk_client import _resolve_sentry_auth_token
        from config.enums import SessionType

        monkeypatch.setenv("SENTRY_PERSONAL_TOKEN", "harness-sentry-token-xyz")
        pm = _make_session("pm", "pm-sentry-001", redis_test_db)

        _harness_env: dict[str, str] = {}
        if pm.session_type in (SessionType.PM, SessionType.TEAMMATE):
            tok = _resolve_sentry_auth_token()
            if tok:
                _harness_env["SENTRY_AUTH_TOKEN"] = tok

        assert _harness_env["SENTRY_AUTH_TOKEN"] == "harness-sentry-token-xyz"

    def test_dev_session_does_not_get_telegram_chat_id(self, monkeypatch, redis_test_db):
        """Issue #1148 negative test: dev sessions never get PM-only env vars.

        Prevents future regressions that accidentally widen the injection guard.
        """
        from agent.sdk_client import _resolve_sentry_auth_token
        from config.enums import SessionType

        monkeypatch.setenv("SENTRY_PERSONAL_TOKEN", "should-not-appear")
        dev = _make_session("dev", "dev-no-pm-env-001", redis_test_db)

        _harness_env: dict[str, str] = {}
        # Mirror the guarded blocks in session_executor.py:1335 + 1340-1346
        _session_type = dev.session_type
        if _session_type in (SessionType.PM, SessionType.TEAMMATE) and dev.agent_session_id:
            _harness_env["VALOR_PARENT_SESSION_ID"] = dev.agent_session_id
        if _session_type in (SessionType.PM, SessionType.TEAMMATE):
            if dev.chat_id:
                _harness_env["TELEGRAM_CHAT_ID"] = str(dev.chat_id)
            tok = _resolve_sentry_auth_token()
            if tok:
                _harness_env["SENTRY_AUTH_TOKEN"] = tok

        assert "TELEGRAM_CHAT_ID" not in _harness_env
        assert "SENTRY_AUTH_TOKEN" not in _harness_env
        assert "VALOR_PARENT_SESSION_ID" not in _harness_env
