# Generated by Django 3.1 on 2020-10-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0003_auto_20201014_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotmembership',
            name='bot_username',
        ),
        migrations.AddField(
            model_name='telegrambotmembership',
            name='expectations_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='telegrambotmembership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_bot_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
