"""
Daydream Report - GitHub Issue Creation

Creates GitHub issues from daydream findings using the `gh` CLI.
Designed to be imported by the main daydream runner or used standalone.
"""

from __future__ import annotations

import logging
import subprocess

logger = logging.getLogger("daydream.report")


def format_report_body(findings: dict[str, list[str]], date: str) -> str:
    """Format daydream findings into a GitHub issue body.

    Args:
        findings: Dict mapping category names to lists of finding strings.
        date: The date string (YYYY-MM-DD) for the report.

    Returns:
        Formatted markdown body for the GitHub issue.
    """
    # Filter out empty categories
    active_findings = {k: v for k, v in findings.items() if v}

    if not active_findings:
        return f"# Daydream Report - {date}\n\nNo significant findings today."

    lines = [f"# Daydream Report - {date}", ""]

    for category, items in active_findings.items():
        title = category.replace("_", " ").title()
        lines.append(f"## {title}")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Auto-generated by daydream on {date}*")

    return "\n".join(lines)


def issue_exists_for_date(date: str) -> bool:
    """Check if a daydream issue already exists for the given date.

    Args:
        date: The date string (YYYY-MM-DD) to check.

    Returns:
        True if an issue already exists, False otherwise.
    """
    try:
        result = subprocess.run(
            [
                "gh",
                "issue",
                "list",
                "--label",
                "daydream",
                "--search",
                f"Daydream Report - {date}",
                "--state",
                "all",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.returncode == 0 and bool(result.stdout.strip())
    except Exception as e:
        logger.warning(f"Could not check for existing issue: {e}")
        return False


def create_daydream_issue(findings: dict[str, list[str]], date: str) -> bool:
    """Create a GitHub issue with daydream findings.

    Skips creation if:
    - An issue already exists for this date
    - There are no real findings (all categories empty)

    Args:
        findings: Dict mapping category names to lists of finding strings.
        date: The date string (YYYY-MM-DD) for the report.

    Returns:
        True if issue was created, False if skipped or failed.
    """
    # Skip if no real findings
    active_findings = {k: v for k, v in findings.items() if v}
    if not active_findings:
        logger.info("No findings to report, skipping issue creation")
        return False

    # Skip if issue already exists
    if issue_exists_for_date(date):
        logger.info(f"Daydream issue already exists for {date}, skipping")
        return False

    # Format and create
    title = f"Daydream Report - {date}"
    body = format_report_body(findings, date)

    try:
        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--label",
                "daydream",
                "--body",
                body,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            issue_url = result.stdout.strip()
            logger.info(f"Created daydream issue: {issue_url}")
            return True
        else:
            logger.error(f"Failed to create issue: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Error creating GitHub issue: {e}")
        return False
