"""
Reflections Report - GitHub Issue Creation

Creates GitHub issues from reflections findings using the `gh` CLI.
Designed to be imported by the main reflections runner or used standalone.

See docs/features/reflections.md for full documentation.
"""

from __future__ import annotations

import logging
import subprocess

logger = logging.getLogger("reflections.report")

# In-memory dedup guard: tracks (date, cwd) tuples created during the current
# reflections run. Prevents duplicate issue creation when multiple projects are
# processed rapidly and GitHub's search index hasn't updated yet.
_created_this_run: set[tuple[str, str | None]] = set()


def reset_dedup_guard() -> None:
    """Clear the in-memory dedup guard.

    Call at the start of each reflections run to ensure a clean slate,
    and in tests to reset state between test cases.
    """
    _created_this_run.clear()


def format_report_body(findings: dict[str, list[str]], date: str) -> str:
    """Format reflections findings into a GitHub issue body.

    Args:
        findings: Dict mapping category names to lists of finding strings.
        date: The date string (YYYY-MM-DD) for the report.

    Returns:
        Formatted markdown body for the GitHub issue.
    """
    # Filter out empty categories
    active_findings = {k: v for k, v in findings.items() if v}

    if not active_findings:
        return f"# Reflections Report - {date}\n\nNo significant findings today."

    lines = [f"# Reflections Report - {date}", ""]

    for category, items in active_findings.items():
        title = category.replace("_", " ").title()
        lines.append(f"## {title}")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Auto-generated by reflections on {date}*")

    return "\n".join(lines)


def issue_exists_for_date(date: str, cwd: str | None = None) -> bool:
    """Check if a reflections issue already exists for the given date.

    Args:
        date: The date string (YYYY-MM-DD) to check.
        cwd: Optional working directory for the gh CLI subprocess. Must match
            the cwd used for issue creation to check the correct repo.

    Returns:
        True if an issue already exists, False otherwise.
    """
    try:
        result = subprocess.run(
            [
                "gh",
                "issue",
                "list",
                "--label",
                "reflections",
                "--search",
                f"Reflections Report - {date}",
                "--state",
                "all",
            ],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=cwd,
        )
        return result.returncode == 0 and bool(result.stdout.strip())
    except Exception as e:
        logger.warning(f"Could not check for existing issue: {e}")
        return False


def create_reflections_issue(
    findings: dict[str, list[str]], date: str, cwd: str | None = None
) -> str | bool:
    """Create a GitHub issue with reflections findings.

    Skips creation if:
    - An issue already exists for this date (checked via gh in the correct repo)
    - The in-memory dedup guard already recorded a creation for this date+cwd
    - There are no real findings (all categories empty)

    Args:
        findings: Dict mapping category names to lists of finding strings.
        date: The date string (YYYY-MM-DD) for the report.
        cwd: Optional working directory for the gh CLI subprocess. Useful
            for multi-repo support where each project has its own gh context.

    Returns:
        Issue URL string if issue was created, False if skipped or failed.
    """
    # Skip if no real findings
    active_findings = {k: v for k, v in findings.items() if v}
    if not active_findings:
        logger.info("No findings to report, skipping issue creation")
        return False

    # Skip if already created during this run (race condition guard)
    dedup_key = (date, cwd)
    if dedup_key in _created_this_run:
        logger.info(f"Reflections issue already created this run for {date} (cwd={cwd}), skipping")
        return False

    # Skip if issue already exists in the target repo
    if issue_exists_for_date(date, cwd=cwd):
        logger.info(f"Reflections issue already exists for {date}, skipping")
        return False

    # Format and create
    title = f"Reflections Report - {date}"
    body = format_report_body(findings, date)

    try:
        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--label",
                "reflections",
                "--body",
                body,
            ],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=cwd,
        )
        if result.returncode == 0:
            issue_url = result.stdout.strip()
            logger.info(f"Created reflections issue: {issue_url}")
            # Record in dedup guard to prevent race condition duplicates
            _created_this_run.add(dedup_key)
            return issue_url
        else:
            logger.error(f"Failed to create issue: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Error creating GitHub issue: {e}")
        return False
